version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition 
      --index-date-range "2019-01-01 to 2022-02-01 by month" 
      --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition
      --output-dir=output
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measure_*_rate.csv

  get_counts:
    run: python:latest python analysis/combine_operators.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        counts: output/*_count.csv

  generate_plots:
    run: python:latest python analysis/plot_measures.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        counts: output/figures/plot_*.jpeg