version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2019-03-01 by month" --skip-existing --output-dir=output/measures --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.feather

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/measures --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/measures/input_ethnicity.feather

  join_ethnicity_all_patients:
    run: python:latest python analysis/join_ethnicity.py --output-dir=output/measures --output-format feather
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/measures/input_20*.feather

  
  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population, generate_study_population_ethnicity, join_ethnicity_all_patients]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv


