version: "3.0"

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --index-date-range "2019-01-01 to 2021-01-01 by month"
      --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

#  generate_study_population_2:
#    run: cohortextractor:latest generate_cohort 
#      --study-definition study_definition 
#      --index-date-range "2021-02-01 to 2022-05-01 by month" 
#      --output-format csv.gz
#    outputs:
#      highly_sensitive:
#        cohort: output/inpu*.csv.gz

  generate_study_population_ethnicity_ukrr:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_ethnicity_ukrr
      --output-dir=output
      --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity_ukrr.csv.gz

  join_cohorts:
    run: >
      cohort-joiner:v0.0.46
        --lhs output/input_20*.csv.gz
        --rhs output/input_ethnicity_ukrr.csv.gz
        --output-dir output/joined
    needs: [generate_study_population, generate_study_population_ethnicity_ukrr]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_20*.csv.gz

  generate_study_population_paeds:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_paeds
      --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_paeds.csv.gz

  generate_table_1:
    run: python:latest python analysis/table_1.py --study_def_paths="output/joined/input_*.csv.gz" --demographics="age_band,sex,region,imd,ethnicity"
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        counts: output/table_1.csv
        at_risk: output/table_1_at_risk.csv

  generate_measures:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition
      --output-dir=output/joined
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        measure_csv: output/joined/measure_*_rate.csv
        
  get_counts:
    run: python:latest python analysis/combine_operators.py
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        counts: output/*_count.csv

  generate_plots:
    run: python:latest python analysis/plot_measures.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        counts: output/figures/plot_*.jpeg

  generate_plots_numeric_values:
    run: python:latest python analysis/plot_numeric_values.py
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        figures: output/*dis*.jpeg


  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/report.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [generate_plots, get_counts]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/report.html

  generate_ukrr_checks:
    run: r:latest -e 'rmarkdown::render("analysis/ukrr-analysis/ukrr-checks.Rmd", knit_root_dir = "/workspace", output_dir = "output/notebooks")'
    needs: [generate_study_population, generate_study_population_ethnicity_ukrr]
    outputs:
      moderately_sensitive:
        report: output/notebooks/ukrr-checks.html

  generate_ukrr_report:
    run: r:latest -e 'rmarkdown::render("analysis/ukrr-analysis/ukrr-report.Rmd", knit_root_dir = "/workspace", output_dir = "output/notebooks")'
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        report: output/notebooks/ukrr-report.html
       
  generate_ukrr_discrepancies:
    run: r:latest -e 'rmarkdown::render("analysis/ukrr-analysis/ukrr-discrepancies.Rmd", knit_root_dir = "/workspace", output_dir = "output/notebooks")'
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        report: output/notebooks/ukrr-discrepancies.html
  
  # generate_kidney_week:
  #   run: r:latest -e 'rmarkdown::render("analysis/ukrr-analysis/kidney_week.Rmd", knit_root_dir = "/workspace", output_dir = "output/notebooks")'
  #   needs: [join_cohorts]
  #   outputs:
  #     moderately_sensitive:
  #       report: output/notebooks/kidney_week.html
  
  generate_ukrr_tables_figures:
    run: r:latest -e 'rmarkdown::render("analysis/ukrr-analysis/ukrr-tables-figures.Rmd", knit_root_dir = "/workspace", output_dir = "output/notebooks")'
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        report: output/notebooks/ukrr-tables-figures.html

  generate_ukrr_tables_figures_paeds:
    run: r:latest -e 'rmarkdown::render("analysis/ukrr-analysis/ukrr-tables-figures-paeds.Rmd", knit_root_dir = "/workspace", output_dir = "output/notebooks")'
    needs: [generate_study_population_paeds]
    outputs:
      moderately_sensitive:
        report: output/notebooks/ukrr-tables-figures-paeds.html
  
 # generate_frequency_plots:
 #   run: r:latest analysis/test_frequency.R
 #   needs: [join_cohorts]
 #   outputs:
 #     moderately_sensitive:
 #       figures: output/figures/months_with_*.png
