version: "3.0"

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition 
      --index-date-range "2019-01-01 to 2022-02-01 by month" 
      --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  generate_study_population_rrt:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_rrt
      --index-date-range "2019-01-01 to 2022-02-01 by month" 
      --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_rrt*.csv.gz

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_ethnicity
      --output-dir=output
      --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

  join_cohorts:
    run: >
      cohort-joiner:v0.0.9
        --lhs output/input_20*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_20*.csv.gz

  join_cohorts_rrt:
    run: >
      cohort-joiner:v0.0.9
        --lhs output/input_rrt_20*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/joined
    needs: [generate_study_population_rrt, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_rrt_20*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition
      --output-dir=output/joined
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        measure_csv: output/joined/measure_*_rate.csv

  generate_measures_rrt:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_rrt
      --output-dir=output/joined
    needs: [join_cohorts_rrt]
    outputs:
      moderately_sensitive:
        measure_csv: output/joined/measure*_rate.csv

  get_counts:
    run: python:latest python analysis/combine_operators.py
    needs: [join_cohorts]
    outputs:
      moderately_sensitive:
        counts: output/*_count.csv

  generate_plots:
    run: python:latest python analysis/plot_measures.py
    needs: [generate_measures, generate_measures_rrt]
    outputs:
      moderately_sensitive:
        counts: output/figures/plot_*.jpeg

