---
title: "PC and SC codes 3"
author: "Shalini Santhakumaran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load libraries
library(tidyverse)
library(knitr)
library(kableExtra)

# Create directory if it doesnt exist
fs::dir_create(here::here("output", "notebooks"))

demogs<-c("age_band", "sex", "ethnicity", "imd", "diabetes", "hypertension",  "at_risk", "region")

#read in dataset
#pick up 1st Jan cohort as latest renal status is on or before index date
 df<-read.csv(here::here("output", "ukrr", "input_ukrr_2020-01-01.csv.gz")) 

#getting year of start for incident start dates
inc_year_pc<-as.numeric(substr(df$incident_rrt_date,1,4))
inc_year_sc<-as.numeric(substr(df$incident_rrt_date_secondary,1,4))
#ukrr - start dates are stored in different variables, start with inc 2020 then look at prevalent cohorts, replacing missing values only
#will be consistent as we only have one start date per patient in the data that was sent
inc_year_ukrr<-as.numeric(substr(df$ukrr_inc2020_date,1,4))
inc_year_ukrr[is.na(inc_year_ukrr)]<-as.numeric(substr(df[is.na(inc_year_ukrr),]$ukrr_2019_startdate,1,4))
inc_year_ukrr[is.na(inc_year_ukrr)]<-as.numeric(substr(df[is.na(inc_year_ukrr),]$ukrr_2020_startdate,1,4))
inc_year_ukrr[is.na(inc_year_ukrr)]<-as.numeric(substr(df[is.na(inc_year_ukrr),]$ukrr_2021_startdate,1,4))
 
 #only keep incident data for 2020 for PC and SC
df<-df %>%
  mutate(incident_rrt_status=ifelse(grepl("2020",incident_rrt_date), incident_rrt_status, "" )) %>%
  mutate(incident_rrt_status_secondary=ifelse(grepl("2020",incident_rrt_date_secondary), incident_rrt_status_secondary, "" ))

#find nearest event to UKRR start date
df<-df%>%
  mutate(nearest_rrt_code = ifelse(ukrr_inc2020==0, "Not inc in UKRR",
                          ifelse(next_before_allRRT=="" & next_after_allRRT=="", "No events",
                            ifelse(next_before_allRRT=="", next_after_allRRT,
                                ifelse(next_after_allRRT=="", next_before_allRRT,
                                  ifelse(as.Date(ukrr_inc2020_date, "%Y-%m-%d") - as.Date(next_before_allRRT_date, "%Y-%m-%d")
                                       < as.Date(next_after_allRRT_date,"%Y-%m-%d") - as.Date(ukrr_inc2020_date, "%Y-%m-%d"), 
                                       next_before_allRRT, next_after_allRRT))))))

#add variable for dialysis/tx for UKRR
df<- df %>%
  mutate(ukrr_dtx = ifelse(ukrr_2019_mod %in% c("ICHD", "HD", "HHD", "PD") , "Dialysis", ifelse(ukrr_2019_mod == "Tx", "Transplant", "Not on RRT"))) %>%
  mutate(ukrr_dtx_inc = ifelse(ukrr_inc2020_mod %in% c("ICHD", "HD", "HHD", "PD") , "Dialysis", ifelse(ukrr_inc2020_mod == "Tx", "Transplant", "Not on RRT"))) %>%
  mutate(region = replace(region, region=="", "Missing"))
# order factor
df$ukrr_dtx<-factor(df$ukrr_dtx, levels=c("Not on RRT", "Dialysis", "Transplant"))
df$ukrr_dtx_inc<-factor(df$ukrr_dtx_inc, levels=c("Not on RRT", "Dialysis", "Transplant"))

# add variable for source
df <- df %>%
  mutate(source_prev_rrt = case_when(ukrr_2019==1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "UPS",
                                      ukrr_2019!=1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "PS",
                                     ukrr_2019==1 & 
                                      !(latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "US",
                                     ukrr_2019==1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      !(latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "UP",
                                     ukrr_2019==1 & 
                                      !(latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      !(latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "U",
                                     ukrr_2019!=1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      !(latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "P",
                                     ukrr_2019!=1 & 
                                      !(latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "S")) %>%
  mutate(source_prev_dialysis = case_when(ukrr_dtx=="Dialysis" & 
                                      latest_rrt_status  =="Dialysis" &
                                      latest_rrt_status_secondary =="Dialysis" ~ "UPS",
                                      ukrr_dtx!="Dialysis" & 
                                      latest_rrt_status  =="Dialysis" &
                                      latest_rrt_status_secondary =="Dialysis" ~ "PS",
                                     ukrr_dtx=="Dialysis" & 
                                      !(latest_rrt_status  =="Dialysis") &
                                      latest_rrt_status_secondary =="Dialysis" ~ "US",
                                     ukrr_dtx=="Dialysis" & 
                                      latest_rrt_status  =="Dialysis" &
                                      !(latest_rrt_status_secondary =="Dialysis") ~ "UP",
                                     ukrr_dtx=="Dialysis" & 
                                      !(latest_rrt_status  =="Dialysis") &
                                      !(latest_rrt_status_secondary =="Dialysis") ~ "U",
                                     ukrr_dtx!="Dialysis" & 
                                      latest_rrt_status  =="Dialysis" &
                                      !(latest_rrt_status_secondary =="Dialysis") ~ "P",
                                     ukrr_dtx!="Dialysis" & 
                                      !(latest_rrt_status  =="Dialysis") &
                                      latest_rrt_status_secondary =="Dialysis" ~ "S")) %>%  
    mutate(source_prev_transplant = case_when(ukrr_dtx=="Transplant" & 
                                      latest_rrt_status  =="Transplant" &
                                      latest_rrt_status_secondary =="Transplant" ~ "UPS",
                                      ukrr_dtx!="Transplant" & 
                                      latest_rrt_status  =="Transplant" &
                                      latest_rrt_status_secondary =="Transplant" ~ "PS",
                                     ukrr_dtx=="Transplant" & 
                                      !(latest_rrt_status  =="Transplant") &
                                      latest_rrt_status_secondary =="Transplant" ~ "US",
                                     ukrr_dtx=="Transplant" & 
                                      latest_rrt_status  =="Transplant" &
                                      !(latest_rrt_status_secondary =="Transplant") ~ "UP",
                                     ukrr_dtx == "Transplant" & 
                                      !(latest_rrt_status  =="Transplant") &
                                      !(latest_rrt_status_secondary =="Transplant") ~ "U",
                                     ukrr_dtx!="Transplant" & 
                                      latest_rrt_status  =="Transplant" &
                                      !(latest_rrt_status_secondary =="Transplant") ~ "P",
                                     ukrr_dtx!="Transplant" & 
                                      !(latest_rrt_status  =="Transplant") &
                                      latest_rrt_status_secondary =="Transplant" ~ "S")) %>%  
    mutate(source_inc_rrt = case_when(ukrr_inc2020==1 & 
                                      incident_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      incident_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "UPS",
                                      ukrr_inc2020!=1 & 
                                      incident_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      incident_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "PS",
                                     ukrr_inc2020==1 & 
                                      !(incident_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      incident_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "US",
                                     ukrr_inc2020==1 & 
                                      incident_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      !(incident_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "UP",
                                     ukrr_inc2020==1 & 
                                      !(incident_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      !(incident_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "U",
                                     ukrr_inc2020!=1 & 
                                      incident_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      !(incident_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "P",
                                     ukrr_inc2020!=1 & 
                                      !(incident_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      incident_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "S")) %>%
  mutate(source_inc_dialysis = case_when(ukrr_dtx_inc=="Dialysis" & 
                                      incident_rrt_status  =="Dialysis" &
                                      incident_rrt_status_secondary =="Dialysis" ~ "UPS",
                                      ukrr_dtx_inc!="Dialysis" & 
                                      incident_rrt_status  =="Dialysis" &
                                      incident_rrt_status_secondary =="Dialysis" ~ "PS",
                                     ukrr_dtx_inc=="Dialysis" & 
                                      !(incident_rrt_status  =="Dialysis") &
                                      incident_rrt_status_secondary =="Dialysis" ~ "US",
                                     ukrr_dtx_inc=="Dialysis" & 
                                      incident_rrt_status  =="Dialysis" &
                                      !(incident_rrt_status_secondary =="Dialysis") ~ "UP",
                                     ukrr_dtx_inc == "Dialysis" & 
                                      !(incident_rrt_status  =="Dialysis") &
                                      !(incident_rrt_status_secondary =="Dialysis") ~ "U",
                                     ukrr_dtx_inc!="Dialysis" & 
                                      incident_rrt_status  =="Dialysis" &
                                      !(incident_rrt_status_secondary =="Dialysis") ~ "P",
                                     ukrr_dtx_inc!="Dialysis" & 
                                      !(incident_rrt_status  =="Dialysis") &
                                      incident_rrt_status_secondary =="Dialysis" ~ "S")) %>%  
    mutate(source_inc_transplant = case_when(ukrr_dtx_inc=="Transplant" & 
                                      incident_rrt_status  =="Transplant" &
                                      incident_rrt_status_secondary =="Transplant" ~ "UPS",
                                      ukrr_dtx_inc!="Transplant" & 
                                      incident_rrt_status  =="Transplant" &
                                      incident_rrt_status_secondary =="Transplant" ~ "PS",
                                     ukrr_dtx_inc=="Transplant" & 
                                      !(incident_rrt_status  =="Transplant") &
                                      incident_rrt_status_secondary =="Transplant" ~ "US",
                                     ukrr_dtx_inc=="Transplant" & 
                                      incident_rrt_status  =="Transplant" &
                                      !(incident_rrt_status_secondary =="Transplant") ~ "UP",
                                     ukrr_dtx_inc == "Transplant" & 
                                      !(incident_rrt_status  =="Transplant") &
                                      !(incident_rrt_status_secondary =="Transplant") ~ "U",
                                     ukrr_dtx_inc!="Transplant" & 
                                      incident_rrt_status  =="Transplant" &
                                      !(incident_rrt_status_secondary =="Transplant") ~ "P",
                                     ukrr_dtx_inc!="Transplant" & 
                                      !(incident_rrt_status  =="Transplant") &
                                      incident_rrt_status_secondary =="Transplant" ~ "S"))

# pick out latest RRT code for primary care
df<-df %>%
    mutate(latest_rrt_code = ifelse(latest_rrt_status=="None", "None",
                                  ifelse(latest_rrt_status=="Dialysis", dialysis_code,
                                      ifelse(latest_rrt_status=="Transplant", kidney_tx_code,
                                             ifelse(latest_rrt_status=="RRT_unknown", RRT_code,"Uncategorised")))))

# pick out incident RRT code for primary care
df<-df %>%
    mutate(incident_rrt_code = ifelse(incident_rrt_status=="None", "None",
                                  ifelse(incident_rrt_status=="Dialysis", earliest_dialysis_code,
                                      ifelse(incident_rrt_status=="Transplant", earliest_kidney_tx_code,
                                             ifelse(incident_rrt_status=="RRT_unknown", earliest_RRT_code,"Uncategorised")))))



# order factor
source_levels<-c("UPS", "UP", "US", "PS", "U", "P", "S")
df$source_prev_rrt<-factor(df$source_prev_rrt, levels=source_levels)
df$source_prev_dialysis<-factor(df$source_prev_dialysis, levels=source_levels)
df$source_prev_transplant<-factor(df$source_prev_transplant, levels=source_levels)
df$source_inc_rrt<-factor(df$source_inc_rrt, levels=source_levels)
df$source_inc_dialysis<-factor(df$source_inc_dialysis, levels=source_levels)
df$source_inc_transplant<-factor(df$source_inc_transplant, levels=source_levels)

#read in codelists so we can tabulate the names
dialysis_codelist<-unique(read.csv(here::here("codelists", "opensafely-dialysis.csv"))[,1:2])
kidney_tx_codelist<-unique(read.csv(here::here("codelists", "opensafely-kidney-transplant.csv"))[,1:2])
all.codelists<-list(dialysis_codelist, kidney_tx_codelist )


# function to filter dataset to exclude patients with no RRT in either OS or UKRR as this is what we want to show pct by
keepRRT<-function(x){
  filter(x , ukrr_prev==1 | latest_renal_status %in% c("Dialysis", "Transplant", "RRT_unknown"))
}
keepRRT_nockd<-function(x){
  filter(x , ukrr_prev==1 | latest_rrt_status %in% c("Dialysis", "Transplant", "RRT_unknown"))
}

#apply disclosure control - redact if less than 7, then round to nearest 5
disclosure <-function(x, whichmargins=0){
  redact <- 0<x & x<=7  #flag redacted values for later
  x[redact] <- 0  # set redacted to 0
  x<-round(x/5)*5 # round to nearest 5
  if(whichmargins!=0){
    x<-addmargins(x,whichmargins) #add totals
  }
  if(whichmargins==1){
    redact<-rbind(redact, rep(FALSE,ncol(redact))) #add extra row to redaction, otherwise won't blank correctly
  }
  if(whichmargins==2){
    redact<-cbind(redact, rep(FALSE,nrow(redact))) #add extra col to redaction, otherwise won't blank correctly
  }
  x[redact]<-"<=7"  # flag redacted values
  return(x)
}

#list of secondary care code variables for prevalent
SC_vars_prev<-names(df)[grepl('_procp_|_diagp_', names(df))]
#list of variables with critical care info
CC_vars_prev<-names(df)[grepl('_ccp_', names(df))]
#create flag for cc vars
CC_flags_prev<-df[CC_vars_prev]
CC_flags_prev[CC_flags_prev>0]<-1

#list of secondary care code variables for incident
SC_vars_inc<-names(df)[grepl('_proci_|_diagi_', names(df))]
#list of variables with critical care info
CC_vars_inc<-names(df)[grepl('_cci_', names(df))]
#create flag for cc vars
CC_flags_inc<-df[CC_vars_inc]
CC_flags_inc[CC_flags_inc>0]<-1

```

# Section 3 - Nearest primary care code for UKRR incident starters (within 3 months of UKRR start date)

```{r, echo=FALSE, results='asis'}

codes.table.2<-function(df, modality){
  df %>%
    filter(ukrr_inc2020==1 & ukrr_inc2020_mod %in% modality) %>%
    group_by(nearest_rrt_code)%>%
    summarise(n=n()) %>%
    mutate(nearest_rrt_code= replace(nearest_rrt_code, nearest_rrt_code %in% c("", NA) , "Missing")) %>%
      mutate(n=ifelse(n<=7,0,n)) %>% #first replace n<=7 with 0
      mutate(n=round(n/5)*5) %>%  #round to nearest 5
      mutate(Percentage = ifelse(n==0, NA, round(100*n/sum(n), 0))) %>%   #then calculate %s, blanking if n is 0
        arrange(desc(n))  %>% #descending sort by n
      mutate(n=ifelse(n<=5,"<=5",n)) #now replacing <=5 (which is now 0 anyway) with "<=5"
}

   k<- codes.table.2(df, c("ICHD", "HD", "HHD", "PD")) %>%
          kbl(caption="Nearest PC code within 3 months for people incident to dialysis in the UKRR in 2020" , booktabs=TRUE) %>% 
          kable_styling()
  print(k)     

     k<- codes.table.2(df, c("Tx", "Transplant")) %>%
          kbl(caption="Nearest PC code within 3 months for people incident to transplant in the UKRR in 2020" , booktabs=TRUE) %>% 
          kable_styling()
  print(k)    
  
```   
