---
title: "PC and SC codes 1b"
author: "Shalini Santhakumaran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load libraries
library(tidyverse)
library(knitr)
library(kableExtra)

# Create directory if it doesnt exist
fs::dir_create(here::here("output", "notebooks"))

demogs<-c("age_band", "sex", "ethnicity", "imd", "diabetes", "hypertension",  "at_risk", "region")

#read in dataset
#pick up 1st Jan cohort as latest renal status is on or before index date
 df<-read.csv(here::here("output", "ukrr", "input_ukrr_2020-01-01.csv.gz")) 

#add variable for dialysis/tx for UKRR
df<- df %>%
  mutate(ukrr_dtx = ifelse(ukrr_2019_mod %in% c("ICHD", "HD", "HHD", "PD") , "Dialysis", ifelse(ukrr_2019_mod == "Tx", "Transplant", "Not on RRT"))) %>%
  mutate(ukrr_dtx_inc = ifelse(ukrr_inc2020_mod %in% c("ICHD", "HD", "HHD", "PD") , "Dialysis", ifelse(ukrr_inc2020_mod == "Tx", "Transplant", "Not on RRT"))) %>%
  mutate(region = replace(region, region=="", "Missing"))
# order factor
df$ukrr_dtx<-factor(df$ukrr_dtx, levels=c("Not on RRT", "Dialysis", "Transplant"))
df$ukrr_dtx_inc<-factor(df$ukrr_dtx_inc, levels=c("Not on RRT", "Dialysis", "Transplant"))

# add variable for source
df <- df %>%
  mutate(source_prev_rrt = case_when(ukrr_2019==1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "UPS",
                                      ukrr_2019!=1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "PS",
                                     ukrr_2019==1 & 
                                      !(latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "US",
                                     ukrr_2019==1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      !(latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "UP",
                                     ukrr_2019==1 & 
                                      !(latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      !(latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "U",
                                     ukrr_2019!=1 & 
                                      latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown") &
                                      !(latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown")) ~ "P",
                                     ukrr_2019!=1 & 
                                      !(latest_rrt_status  %in%  c("Dialysis", "Transplant", "RRT_unknown")) &
                                      latest_rrt_status_secondary %in% c("Dialysis","Transplant", "RRT_unknown") ~ "S")) 

# pick out latest RRT code for primary care
df<-df %>%
    mutate(latest_rrt_code = ifelse(latest_rrt_status=="None", "None",
                                  ifelse(latest_rrt_status=="Dialysis", dialysis_code,
                                      ifelse(latest_rrt_status=="Transplant", kidney_tx_code,
                                             ifelse(latest_rrt_status=="RRT_unknown", RRT_code,"Uncategorised")))))




# order factor
source_levels<-c("UPS", "UP", "US", "PS", "U", "P", "S")
df$source_prev_rrt<-factor(df$source_prev_rrt, levels=source_levels)

#read in codelists so we can tabulate the names
dialysis_codelist<-unique(read.csv(here::here("codelists", "opensafely-dialysis.csv"))[,1:2])
kidney_tx_codelist<-unique(read.csv(here::here("codelists", "opensafely-kidney-transplant.csv"))[,1:2])
all.codelists<-list(dialysis_codelist, kidney_tx_codelist )



```

# Section 1 PC codes for people prevalent to RRT according to primary care data but not the UKRR

1B And repeating for people who are in the UKRR, for reference

```{r, echo=FALSE, results='asis'}

codes.table<-function(df, grouplist, status, codelist){
  df %>%
    filter(source_prev_rrt %in% grouplist & latest_rrt_status==status) %>%
    group_by(latest_rrt_code)%>%
    summarise(n=n()) %>%
    left_join(codelist, by=setNames(names(codelist)[1], "latest_rrt_code")) %>%
    mutate(latest_rrt_code= replace(latest_rrt_code, latest_rrt_code %in% c("", NA) , "Missing")) %>%
      mutate(n=ifelse(n<=7,0,n)) %>% #first replace n<=7 with 0
      mutate(n=round(n/5)*5) %>%  #round to nearest 5
      mutate(Percentage = ifelse(n==0, NA, round(100*n/sum(n), 0))) %>%   #then calculate %s, blanking if n is 0
        arrange(desc(n))  %>% #descending sort by n
      mutate(n=ifelse(n<=7,"<=7",n)) #now replacing <=7 (which is now 0 anyway) with "<=7"
}

list.of.dts<- mapply(function(y, z) 
    codes.table(df, c("UP", "UPS") , y, z), 
    c("Dialysis", "Transplant"),  all.codelists[1:2], SIMPLIFY=FALSE)

  for(j in 1:2){
   k<- list.of.dts[j]%>%
          kbl(caption=c("Dialysis", "Transplant")[j], booktabs=TRUE) %>% 
          kable_styling()
  print(k)     
  }
```   

